version: '3.4'

services:
  webapp:
    container_name: webapp
    image: webapp
    build:
      context: .
      dockerfile: WebApplication2/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
        - webApp-dev
    depends_on:
       - db
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 123123123123
    ports:
      - "5432:5432"
    networks:
      - webApp-dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  webApp-dev:
    driver: bridge

volumes:
  postgres_data: