version: '3.4'

services:
  webapp:
    image: webapp:dev
    build:
      args:
        BUILD_CONFIGURATION: Debug
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "WebApp"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=/.nuget/fallbackpackages
    volumes:
      - C:\Users\rer99\source\repos\WebApplication2\WebApplication2:/app:rw
      - C:\Users\rer99\source\repos\WebApplication2:/src:rw
      - C:\Users\rer99\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\rer99\.nuget\packages:/.nuget/packages:ro
      - D:\VSShared\NuGetPackages:/.nuget/fallbackpackages:ro
      - C:\Users\rer99\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro
      - C:\Users\rer99\AppData\Roaming\ASP.NET\Https:/home/app/.aspnet/https:ro
      - C:\Users\rer99\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Users\rer99\AppData\Roaming\Microsoft\UserSecrets:/home/app/.microsoft/usersecrets:ro
      - D:\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\linux-x64\net8.0:/VSTools:ro
      - D:\Community\Common7\IDE\CommonExtensions\Microsoft\HotReload:/HotReloadAgent:ro

    entrypoint: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --wait"
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /.nuget/packages --additionalProbingPath /.nuget/fallbackpackages  \"/app/bin/Debug/net8.0/WebApp.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --stop dotnet"
    tty: true